[character]
success_symbol = "[âžœ](bold green)"  
error_symbol = "[âžœ](bold red) "

[username]
style_user = "bold #87ceeb"
show_always = true
format = "[$user]($style)@"

[hostname]
ssh_only = false
disabled = false
style = "bold #77dd77"
format = "[$hostname]($style) | "

[cmd_duration]
min_time = 1
show_milliseconds = false
disabled = false
style = "bold dimmed #26ff8f"
format = "\\[[$duration]($style)\\]"

[directory]
truncation_length = 10
truncate_to_repo = true
style = "bold blue"
read_only ="ðŸ”’"
read_only_style = "bold red"
format = "[$read_only]($read_only_style)[$path]($style) "

[git_branch]
symbol = "î‚  "
truncation_length = 4
truncation_symbol = ""
style = "bold green"

[package]
style = "bold dimmed #e52fd7"
format = "[$symbol$version]($style) "
symbol = "ðŸ“¦ "

[git_status]
style = "bold dimmed white"

[python]
symbol = "Python "

[java]
symbol = "Java "
style = "red"

[nodejs]
symbol = "Node.js "

